### PR TITLE
Use valid category in library.properties

### PR DESCRIPTION
**Pull request by per1234**
The previous category value causes:
```
WARNING: Category 'IO' in library Nokia5110 is not valid. Setting to 'Uncategorized'
```
to be displayed on every compile in Arduino IDE 1.6.,6 or newer.

A valid category value from https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format must be used.

### CODE REVIEW

**Comment by nitins11** [comment]
Hello,

Sorry, I have updated the category to "Display" now and pushed the code. Do I need to create a new tag?

Thanks
Nitin

**Comment by per1234** [comment]
First you will need to change the folder structure of your repository to make it Library Manager compatible. From https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#is-my-git-repo-ok:
>Your repo is OK if its root folder contains file library.properties and the rest of the library source code. If your library is stored in a subfolder, your repo is not OK and we can't include your library in the list.

So you will need to move the library files into the root of the repository rather than having it in the Arduino/libraries subfolder as it is now.

Once that's done you should create a new tag

**Comment by nitins11** [comment]
Ok, please confirm if I understood your message correctly:

What I understood is my repo “Arduino" has further subfolder “libraries" and the “Nokia5110Lib" folder is a subfolder under libraries folder. This
is not the correct structure. I will do the following:

1. I will create a new repo Nokia5110LCDLib and put all the library files under this folder directly along with library.properties file
2. Will push and tag it and share the new link

Is this correct?

Thanks
Nitin

**Comment by per1234** [comment]
> What I understood is my repo “Arduino" has further subfolder “libraries" and the “Nokia5110Lib" folder is a subfolder under libraries folder. This is not the correct structure

Correct

> I will create a new repo Nokia5110LCDLib and put all the library files under this folder directly along with library.properties file

You don't need to create a new repository but it does make sense to rename this repository because "Arduino" isn't terribly descriptive. To rename it you only need to:

1. Open https://github.com/nitins11/Arduino
2. Click on the "Settings" tab near the top of the page.
3. Click the box under "Repository name"
4. Type in the new repository name.
5. Click the "Rename" button.
6. The URL for the previous repository name will automatically redirect to the URL for the new repository.

**Comment by nitins11** [comment]
Done. here is the repo link

https://github.com/nitins11/Nokia5110LCD <https://github.com/nitins11/Nokia5110LCD>

Thanks
Nitin

**Comment by per1234** [comment]
Even though GitHub does redirect URLs after changing the name of a repository, the new folder structure of your repository did break the URL you posted on your Library Manager addition request(https://github.com/arduino/Arduino/issues/5724) so you should update that issue with the new URL.

**Comment by nitins11** [comment]
Updated!

**Pull request merged**
